### ISSUE TITLE
Error! couldn't resolve module/action 'ibmi_sql_query'

### ISSUE THREAD

**Issue by Pradeep3369** [aruba/aos-switch-ansible-collection#15]
![16298751018774692215668362093895](https://user-images.githubusercontent.com/89509342/130742526-5271bdb0-ab41-4f0d-af96-80a5c4602130.jpg)

After launch the template under ansible tower. I getting this error

**Comment by tchiapuziowong** [comment]
Hi @Pradeep3369 ! Can you please share the playbook you're using?
