### ISSUE TITLE
ERROR! couldn't resolve module/action 'archive'. This often indicates a misspelling, missing collection, or incorrect module path.

### ISSUE THREAD

**Issue by mrahim0705** [aruba/aos-switch-ansible-collection#20]
While trying to execute a playbook through AWX received the error message "ERROR! couldn't resolve module/action 'archive'. This often indicates a misspelling, missing collection, or incorrect module path.".  

We followed the install process from the following link: https://computingforgeeks.com/install-and-configure-ansible-awx-on-centos/

While login to the server when you check on the server by issuing "ansible --version" it doesn't return anything.  Do we need to install Ansible separately? I'm new to Ansible and want to launch my job through AWX, but receiving the above error message while using some Ansible modules such as archive.  

Thanks

**Comment by tchiapuziowong** [comment]
hello! We're not able to troubleshoot AWX installation issues but if you have a specific issue with our [AOS-Switch Ansible Collection](https://galaxy.ansible.com/arubanetworks/aos_switch) I can try to assist - I would recommend beginning with Ansible CLI, we have a guide on installing Ansible [here ](https://developer.arubanetworks.com/aruba-aoscx/docs/getting-started-with-ansible-and-aos-cx)- then install the AOS-Switch collection using the following command:
`ansible-galaxy collection install arubanetworks.aos_switch`

Please open a new issue if you have any trouble!
