### ISSUE TITLE
Do all modules work in both REST API mode as well as CLI?

### ISSUE THREAD

**Issue by quistian** [aruba/aos-switch-ansible-collection#32]
I am uncertain from the documentation in the modules section whether all modules work in both API as well as SSH CLI mode. Some modules say API but I've used the SSH mode and the code still seems to work.

**Comment by tchiapuziowong** [comment]
No, if given an incorrect ansible_connection value the module will fail with an error

**Comment by quistian** [comment]
Ok... As I thought. Do individual modules indicate whether they work in both modes (I know some do) or only in one?
