### ISSUE TITLE
ImportError: cannot import name 'display'

### ISSUE THREAD

**Issue by MauvaisJoueur** [aruba/aos-switch-ansible-collection#5]
Hello,

I'm trying to set up ansible to manage devices running arubaOS (16.10+) for the first time.

Running Ansible 2.10.3 in a virtualenv named `ansible-2` locate in user `ansible` home directory (`/home/ansible/ansible-2`). The following packages are installed:

```fish
pip list
Package      Version
------------ ---------
ansible      2.10.3
ansible-base 2.10.3
certifi      2020.11.8
cffi         1.14.3
chardet      3.0.4
cryptography 3.2.1
idna         2.10
Jinja2       2.11.2
MarkupSafe   1.1.1
packaging    20.4
pip          20.2.4
pycparser    2.20
pyparsing    2.4.7
PyYAML       5.3.1
requests     2.25.0
setuptools   50.3.2
six          1.15.0
urllib3      1.26.2
wheel        0.35.1
```

Followed [aos_switch in Ansible Galaxy](https://galaxy.ansible.com/arubanetworks/aos_switch) exactly.

When I run a test playbook, I get the following error:
```
TASK [Show running configuration] *******************************************************************************
<... skipped ...>
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_arubaoss_command_payload_b89ap_k_/ansible_arubaoss_command_payload.zip/ansible_collections/arubanetworks/aos_switch/plugins/module_utils/arubaoss.py", line 45, in <module>
ImportError: cannot import name 'display'

During handling of the above exception, another exception occurred:
<... skipped ...>
ModuleNotFoundError: No module named 'ansible.utils'
<... skipped ...>
```

The file in question: [aos-switch-ansible-collection/arubaoss.py at 76c66acdca16d811fe4db7606965cb72ffd503cc · aruba/aos-switch-ansible-collection](https://github.com/aruba/aos-switch-ansible-collection/blob/76c66acdca16d811fe4db7606965cb72ffd503cc/plugins/module_utils/arubaoss.py)

I've read that the issue appears when Ansible is not installed, but it is as we can see in the `pip list` output. Also I can run other ansible commands no problem.
I've came across this: https://github.com/aruba/aos-switch-ansible-collection/issues/1 but I do not see how this applies to me. python3.6 is bundled in the virtualenv. Everything looks OK.

*Can you help me out?* How to explain that the arubaoss module doesn't find ansible.utils that is built-in and that I can locate:
```fish
locate ansible/utils/display
/home/ansible/ansible-2/lib/python3.6/site-packages/ansible/utils/display.py
```

Is this because the collection is not located into the virtualenv ?
```fish
locate arubaoss_command
/home/ansible/.ansible/collections/ansible_collections/arubanetworks/aos_switch/plugins/modules/arubaoss_command.py
```

Best regards,
MauvaisJoueur

**Comment by craigers521** [comment]
@MauvaisJoueur - the collection doesnt need to live in the venv but ansible needs to know which python environment to use.  Try setting a variable for "ansible_python_interpreter" somewhere in your inventory vars, or set the global interpreter in your ansible.cfg for example: 

```
[defaults]
host_key_checking = False
interpreter_python = /Users/your_user/python-virtual-environments/ansible29/bin/python3
```

just make sure the path points to your venv

**Comment by tchiapuziowong** [comment]
When you're in your virtual environment can you execute `ansible --version` and share those results? I'm curious if Ansible's default python interpreter is not picking up those packages

**Comment by MauvaisJoueur** [comment]
Hello,

Thank you for your help.

> 
> 
> When you're in your virtual environment can you execute `ansible --version` and share those results? I'm curious if Ansible's default python interpreter is not picking up those packages
> 
> Also please ensure the version of the AOS-Switch collection is the latest that's functional on 2.10 - `ansible-galaxy collection install arubanetworks.aos_switch -f`

@tchiapuziowong Here it is
```fish
ansible --version
ansible 2.10.3
  config file = /home/ansible/ansible.d/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/ansible-2/lib/python3.6/site-packages/ansible
  executable location = /home/ansible/ansible-2/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

Yes I've reinstalled `ansible.netcommon` as well as `arubanetworks.aos_switch`:
```fish
ansible-galaxy collection list

# /home/ansible/.ansible/collections/ansible_collections
Collection               Version
------------------------ -------
ansible.netcommon        1.4.1
arubanetworks.aos_switch 1.1.0
```

> 
> 
> @MauvaisJoueur - the collection doesnt need to live in the venv but ansible needs to know which python environment to use. Try setting a variable for "ansible_python_interpreter" somewhere in your inventory vars, or set the global interpreter in your ansible.cfg for example:
> 
> ```
> [defaults]
> host_key_checking = False
> interpreter_python = /Users/your_user/python-virtual-environments/ansible29/bin/python3
> ```
> 
> just make sure the path points to your venv

@craigers521 I've set the ansible environment variable in ansible.cfg:
```ini
[defaults]
<... skipped ...>
interpreter_python = /home/ansible/ansible-2/bin/python
```
I'm sure it's pointing to the right location:
```fish
ls -l /home/ansible/ansible-2/bin/python
lrwxrwxrwx 1 ansible ansible 9 Oct 11 10:22 /home/ansible/ansible-2/bin/python -> python3.6*
```

Now I get the following error, which I can't solve:
```
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1605649892.2713506-2207892-139972631991812/AnsiballZ_arubaoss_command.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1605649892.2713506-2207892-139972631991812/AnsiballZ_arubaoss_command.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1605649892.2713506-2207892-139972631991812/AnsiballZ_arubaoss_command.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.arubanetworks.aos_switch.plugins.modules.arubaoss_command', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_arubaoss_command_payload_xj8a8fbj/ansible_arubaoss_command_payload.zip/ansible_collections/arubanetworks/aos_switch/plugins/modules/arubaoss_command.py", line 228, in <module>
  File "/tmp/ansible_arubaoss_command_payload_xj8a8fbj/ansible_arubaoss_command_payload.zip/ansible_collections/arubanetworks/aos_switch/plugins/modules/arubaoss_command.py", line 183, in main
  File "/tmp/ansible_arubaoss_command_payload_xj8a8fbj/ansible_arubaoss_command_payload.zip/ansible_collections/arubanetworks/aos_switch/plugins/module_utils/arubaoss.py", line 436, in run_cli_commands
  File "/tmp/ansible_arubaoss_command_payload_xj8a8fbj/ansible_arubaoss_command_payload.zip/ansible_collections/arubanetworks/aos_switch/plugins/module_utils/arubaoss.py", line 223, in get_connection
  File "/tmp/ansible_arubaoss_command_payload_xj8a8fbj/ansible_arubaoss_command_payload.zip/ansible/module_utils/connection.py", line 124, in __init__
AssertionError: socket_path must be a value
```

I've disabled firewalld and tried again, without success. A search on the www indicates that it might be because of `ansible_connection`. This parameter is set to `local` in the inventory:
```yaml
<... skipped ...>
# network
aos_edge:
  hosts:
    <hostname2>:
      ansible_host: <IP address2>
aos_core:
  hosts:
    <hostname1>:
      ansible_host: <IP address1>
aos:
  children:
    aos_edge:
    aos_core:
  vars:
    ansible_user: manager
    ansible_password: <password>
    ansible_connection: local  # REST API connection method
```
Note that I know it's bad to have plaintext password set here. This is just for testing purposes. 

REST is enabled on the switches:
```
show rest

 REST Interface - Server Configuration

  REST Interface            : Enabled
  REST Operational Status   : Up
  REST Session Idle Timeout : 600 seconds
  HTTP Access               : Disabled
  HTTPS Access              : Enabled
  SSL Port                  : 443
```

**Comment by craigers521** [comment]
I would verify API is reachable using something like postman, just to make sure you can authenticate and API is working properly.  

Also verify your ansible.cfg or environment variables has this set: 
```
[defaults]
NETWORK_GROUP_MODULES=arubaoss
```

and your group/host vars have:

```
ansible_network_os: arubanetworks.aos_switch.arubaoss
```

**Comment by MauvaisJoueur** [comment]
If I do overwrite the `ansible_connection` variable in the playbook:
```yaml
    ansible_connection: network_cli
```
Or
```yaml
    ansible_connection: ansible.netcommon.network_cli
```

I get the following error:
```
fatal: [<hostname>]: FAILED! => {
    "msg": "network os arubanetworks.arubaoss is not supported"
}
```

**Comment by MauvaisJoueur** [comment]
> 
> 
> and your group/host vars have:
> 
> ```
> ansible_network_os: arubanetworks.aos_switch.arubaoss
> ```

@craigers521 I typed `arubanetworks.arubaoss` instead of `arubanetworks.aos_switch.arubaoss`! The playbook played successfully. Thank you so much, both of you.
