### ISSUE TITLE
aruba / aruba-ansibl-Error arubaoss_dsnoop -(arubaoss_required_if)

### ISSUE THREAD

**Issue by FOSSDOM** [aruba/aos-switch-ansible-collection#7]
Aruba : 2930M-48G-PoE+  JL322A  
FW: WC.16.10.0012
Ansible 2.9.6

Cannot configure dhcp snooping on ansible with arubaoss
https://github.com/aruba/aruba-ansible-modules/blob/master/module_documentation/arubaoss/arubaoss_dsnoop.md

- name: enable dsnoop
  arubaoss_dsnoop:
    dsnoop: true

- name: disable dsnoop
  arubaoss_dsnoop:
    dsnoop: false

- name: enable dsnoop option82 with untrusted-policy keep remote-id subnet-ip
  arubaoss_dsnoop:
    command: option_82
    is_dsnoop_option82_enabled: true
    remote_id: "DRI_SUBNET_IP"
    untrusted_policy: "DUP_KEEP"

- name: disable dsnoop option82
  arubaoss_dsnoop:
    command: option_82
    is_dsnoop_option82_enabled: false

- name: add dsnoop authorized_server
  arubaoss_dsnoop:
    command: authorized_server
    server_ip: "30.0.0.1"

- name: remove dsnoop authorized_server
  arubaoss_dsnoop:
    command: authorized_server
    server_ip: "30.0.0.1"
    config: "delete"

----------------------------------------------------------------------------------------------------------------------

Error --vvv

The full traceback is:
Traceback (most recent call last):
File "/home/ansible/.ansible/tmp/ansible-tmp-1613275259.6505885-259405060885273/AnsiballZ_arubaoss_dsnoop.py", line 102, in <module>
_ansiballz_main()
File "/home/ansible/.ansible/tmp/ansible-tmp-1613275259.6505885-259405060885273/AnsiballZ_arubaoss_dsnoop.py", line 94, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File "/home/ansible/.ansible/tmp/ansible-tmp-1613275259.6505885-259405060885273/AnsiballZ_arubaoss_dsnoop.py", line 40, in invoke_module
runpy.run_module(mod_name='ansible.modules.network.arubaoss.arubaoss_dsnoop', init_globals=None, run_name='__main__', alter_sys=True)
File "/usr/lib/python3.8/runpy.py", line 207, in run_module
return _run_module_code(code, init_globals, run_name, mod_spec)
File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
_run_code(code, mod_globals, init_globals,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/tmp/ansible_arubaoss_dsnoop_payload_jwkn_249/ansible_arubaoss_dsnoop_payload.zip/ansible/modules/network/arubaoss/arubaoss_dsnoop.py", line 255, in <module>
File "/tmp/ansible_arubaoss_dsnoop_payload_jwkn_249/ansible_arubaoss_dsnoop_payload.zip/ansible/modules/network/arubaoss/arubaoss_dsnoop.py", line 251, in main
File "/tmp/ansible_arubaoss_dsnoop_payload_jwkn_249/ansible_arubaoss_dsnoop_payload.zip/ansible/modules/network/arubaoss/arubaoss_dsnoop.py", line 229, in run_module
NameError: name 'arubaoss_required_if' is not defined
fatal: [switch1]: FAILED! => {
"changed": false,
"module_stderr": "Traceback (most recent call last):\n File \"/home/ansible/.ansible/tmp/ansible-tmp-1613275259.6505885-259405060885273/AnsiballZ_arubaoss_dsnoop.py\", line 102, in <module>\n _ansiballz_main()\n File \"/home/ansible/.ansible/tmp/ansible-tmp-1613275259.6505885-259405060885273/AnsiballZ_arubaoss_dsnoop.py\", line 94, in _ansiballz_main\n invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n File \"/home/ansible/.ansible/tmp/ansible-tmp-1613275259.6505885-259405060885273/AnsiballZ_arubaoss_dsnoop.py\", line 40, in invoke_module\n runpy.run_module(mod_name='ansible.modules.network.arubaoss.arubaoss_dsnoop', init_globals=None, run_name='__main__', alter_sys=True)\n File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n return _run_module_code(code, init_globals, run_name, mod_spec)\n File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n _run_code(code, mod_globals, init_globals,\n File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n exec(code, run_globals)\n File \"/tmp/ansible_arubaoss_dsnoop_payload_jwkn_249/ansible_arubaoss_dsnoop_payload.zip/ansible/modules/network/arubaoss/arubaoss_dsnoop.py\", line 255, in <module>\n File \"/tmp/ansible_arubaoss_dsnoop_payload_jwkn_249/ansible_arubaoss_dsnoop_payload.zip/ansible/modules/network/arubaoss/arubaoss_dsnoop.py\", line 251, in main\n File \"/tmp/ansible_arubaoss_dsnoop_payload_jwkn_249/ansible_arubaoss_dsnoop_payload.zip/ansible/modules/network/arubaoss/arubaoss_dsnoop.py\", line 229, in run_module\nNameError: name 'arubaoss_required_if' is not defined\n",
"module_stdout": "",
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
"rc": 1
}

![dsnoop](https://user-images.githubusercontent.com/38142792/108102852-1e6f2c00-7057-11eb-8b54-73f76c77fc35.png)

**Comment by tchiapuziowong** [comment]
Hi @ssdsmart I'm sorry but the playbook seems to be a little messed up with the paste- could you please paste again? I'm able to configure DHCP-snooping as well as authorize servers with the following playbook & information.
Aruba : 2930M
FW: WC.16.10.0002
Ansible 2.9.6

Playbook:
```
---
- hosts: all
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: enable dsnoop
      arubaoss_dsnoop:
        dsnoop: true

    - name: add dsnoop authorized_server
      arubaoss_dsnoop:
        command: authorized_server
        server_ip: "10.100.100.100"
    - name: add dsnoop authorized_server
      arubaoss_dsnoop:
        command: authorized_server
        server_ip: "10.200.200.200"
```

Resulting Configuration:
```
2930M-Ansible-Demo-01# show dhcp-snooping

 DHCP Snooping Information

  DHCP Snooping              : Yes
  Enabled VLANs              :
  Verify MAC address         : Yes
  Option 82 untrusted policy : drop
  Option 82 insertion        : Yes
  Option 82 remote-id        : mac
  Store lease database       : Not configured
  Rate-Limit (PPS)           : 100

  Authorized Servers
  ------------------
  10.100.100.100
  10.200.200.200
```

Also please make sure you're using the AOS-Switch collection and properly using it in the playbook like so: https://github.com/aruba/aos-switch-ansible-collection#example-playbook
